version: '3.3'

services:
  icinga2:
    image: bastidest/icinga2:${GIT_REF_ICINGA2}
    build:
      context: ./context
      dockerfile: icinga.Dockerfile
      args:
        - GIT_REF_ICINGA2=${GIT_REF_ICINGA2}
        - GIT_REF_ICINGAWEB2=${GIT_REF_ICINGAWEB2}
    hostname: 'icinga2'
    env_file:
      - ./common.env
      - ./icinga.env
    ports:
      - 80:80
      - 5665:5665
    volumes:
      - ./data/icinga2/etc:/usr/local/icinga2/etc/icinga2
      - ./data/icinga2/lib:/usr/local/icinga2/var/lib

  mysql:
    image: bastidest/icinga2-mysql:${GIT_REF_ICINGA2}
    build:
      context: ./context
      dockerfile: mysql.Dockerfile
      args:
        - GIT_REF_ICINGA2=${GIT_REF_ICINGA2}
        - GIT_REF_ICINGAWEB2=${GIT_REF_ICINGAWEB2}
    env_file:
      - ./common.env
      - ./mysql.env
    command: '/app/start.sh'
    volumes:
      - ./data/mysql/lib:/var/lib/mysql

  graphite:
    image: graphiteapp/docker-graphite-statsd
    volumes:
      - ./context/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro
      - ./context/graphite/graphTemplates.conf:/opt/graphite/conf/graphTemplates.conf:ro
      - ./data/graphite/lib/:/var/lib/graphite
